[workspace]
members = [".", "pedersen-hash"]

[package]
name = "webb"
version = "0.2.5"
edition = "2021"
authors = [
   "Webb Developers <devs@webb.tools>",
   "Shady Khalifa <shekohex@gmail.com>"
]
license = "GPL-3.0"
repository = "https://github.com/webb-tools/webb-rs"
documentation = "https://docs.rs/webb"
homepage = "https://www.webb.tools"
description = "Webb SDK"
keywords = ["webb", "sdk", "blockchain", "webb-tools"]
include = ["Cargo.toml", "contracts/", "metadata/", "src/**/*.rs", "build.rs", "README.md", "LICENSE"]
build = "build.rs"

[dependencies]
# Substrate crates.
scale = { package = "parity-scale-codec", version = "2.3.0", default-features = false, optional = true }
async-trait = "0.1"
rand = { version = "0.8", default-features = false, features = ["getrandom"] }
thiserror = "1.0.26"
hex = { version = "0.4", default-features = false }

# EVM crates.
ethers = { version = "0.6.0", default-features = false, features = ["legacy"], optional = true }
serde_json = { version = "1", optional = true }
pedersen = { version = "0.1", package = "webb-pedersen-hash", path = "pedersen-hash", optional = true }
# just to make it compile on Linux where the OpenSSL is not available.
# So, we just use the vendored one.
native-tls = { version = "^0.2", features = ["vendored"] }

[dependencies.subxt]
git = "https://github.com/paritytech/subxt.git"
version = "0.15.0"
rev = "7aac7dfec" # https://github.com/paritytech/subxt/commit/7aac7dfec
optional = true

[dev-dependencies]
tokio = { version = "^1", features = ["macros", "rt"] }
anyhow = "^1"
sp-keyring = { git = "https://github.com/paritytech/substrate/", branch = "master" }

[build-dependencies]
serde_json = "1"
tempfile = "3.2"
ethers = { version = "0.6.0", default-features = false, features = ["legacy"], optional = true }
syn = { version = "1.0.80", optional = true }
scale = { package = "parity-scale-codec", version = "2.3.0", default-features = false, optional = true }
frame-metadata = { version = "14.0.0", features = ["v14", "std"], optional = true }

[build-dependencies.subxt-codegen]
git = "https://github.com/paritytech/subxt.git"
version = "0.2.0"
rev = "7aac7dfec" # https://github.com/paritytech/subxt/commit/7aac7dfec
optional = true

[features]
default = ["substrate-runtime", "evm-runtime"]
# Main features.
substrate-runtime = ["subxt", "scale"]
evm-runtime = [
    "ethers",
    "serde_json",
    "pedersen"
]

# Tests
integration-tests = []
# Build
generate-contracts = ["evm-runtime"]
generate-substrate = ["subxt-codegen", "syn", "frame-metadata", "scale"]

# sp-core = { package = "sp-core", git = "https://github.com/paritytech/substrate.git", rev = "026ec33f" }
