[package]
name = "pedersen-hash"
version = "0.1.0"
edition = "2018"

[dependencies]

[dev-dependencies]
rand = { version = "0.8", default-features = false, features = ["getrandom"] }
hex = { version = "0.4", default-features = false }
