name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - README.md
      - CHANGELOG.md # Should never be edited anyway
      - .gitignore
      - .github/**
  pull_request:
    branches: [main]
    types: [opened, synchronize, closed]
  workflow_dispatch:

jobs:
  webb:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    # Name should be the OS name only (e.g. Linux, macOS, Windows)
    # This is used to generate the badge
    name: webb crate (${{ matrix.os }})
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Mold Linker
        uses: rui314/setup-mold@v1
      - name: Check Metadata generation
        run: cargo build --features generate-contracts
      - name: Tests
        run: cargo test -p webb
      - name: Rustdoc build
        run: cargo doc -p webb --no-deps --all-features

  proposals:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        features:
          - evm,std,scale
          - evm
        test-features:
          - evm,std,scale
    runs-on: ${{ matrix.os }}
    # Name should be the OS name only (e.g. Linux, macOS, Windows)
    # This is used to generate the badge
    name: proposals crate (${{ matrix.os }} with ${{ matrix.features }} / ${{ matrix.test-features }})
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Mold Linker
        uses: rui314/setup-mold@v1
      - name: Build
        run: cargo build -p webb-proposals --no-default-features --features ${{ matrix.features }}
      - name: Tests
        run: cargo test -p webb-proposals --no-default-features --features ${{ matrix.test-features }}
      - name: Rustdoc
        run: cargo doc -p webb-proposals --no-deps --no-default-features --features ${{ matrix.features }}

  evm-test-utils:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    # Name should be the OS name only (e.g. Linux, macOS, Windows)
    # This is used to generate the badge
    name: evm-test-utils crate (${{ matrix.os }})
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Mold Linker
        uses: rui314/setup-mold@v1
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Download fixtures
        run: |
          mkdir -p ./solidity-fixtures/vanchor_2/2
          curl -L -o ./solidity-fixtures/vanchor_2/2/poseidon_vanchor_2_2.wasm https://dapp-fixtures.s3.amazonaws.com/develop/vanchor_2/2/poseidon_vanchor_2_2.wasm
          curl -L -o ./solidity-fixtures/vanchor_2/2/circuit_final.zkey https://dapp-fixtures.s3.amazonaws.com/develop/vanchor_2/2/circuit_final.zkey

      - name: Tests
        run: cargo test -p webb-evm-test-utils
